### ISSUE TITLE
support more complex condition matching on validonly and condition in the metadata

### ISSUE THREAD

**Issue by lguohan** [opencomputeproject/SAI#1246]
@validonly (A == XA or B == YB) and (C == ZC)

**Comment by kcudnik** [comment]
We discussed this couple years ago, that supporting such complex conditions will actual lead to inventing our own scripting language, to be able to parse this, since currently it's basically regex split on "or/and" and just searching attributes, so there is no need for understanding bracketing. 
Second this is how to write this condition as a structure in metadata, since today we just write attribute ID and attribute expected value.
I think economically developing this parser is not viable, since actually nobody will be this actively using, it's easier just to put right now special case in sairedis metadata for that.
Also since that original attribute that originated in this, is for validonly case, then internal vendor can actually return SAI_STATUS_NOT_SUPPORTED if condition internally is not met, for example speed is not expected etc.

**Comment by kcudnik** [comment]
Fixed in https://github.com/opencomputeproject/SAI/pull/1255

**Comment by kcudnik** [comment]
Merged
