### ISSUE TITLE
1.0 ACL spec bind point type assignments clarification.

### ISSUE THREAD

**Issue by tushar-ty** [opencomputeproject/SAI#498]
In the following documentation/example:

--------------------------------------------
Example 3 - Create an ACL group

This example creates and ACL group with more than one ACL table and bind it to a port, the very same way an ACL table was bound to a port in Example 1.

// CREATE AN INGRESS ACL TABLE GROUP
sai_object_id_t acl_grp_id1 = 0ULL;
acl_grp_attr[0].id = SAI_ACL_TABLE_GROUP_ATTR_ACL_STAGE;
acl_grp_attr[0].value.s32 = SAI_ACL_STAGE_INGRESS;

acl_grp_attr[1].id = SAI_ACL_TABLE_GROUP_ATTR_ACL_BIND_POINT_TYPE_LIST;
acl_grp_attr[1].value.objlist.count = 1;
acl_grp_attr[1].value.objlist.list[0] = SAI_ACL_BIND_POINT_TYPE_PORT;

acl_grp_attr[2].id = SAI_ACL_TABLE_GROUP_ATTR_TYPE;
acl_grp_attr[2].value.s32 = SAI_ACL_TABLE_GROUP_SEQUENTIAL;

saistatus = sai_acl_api->create_acl_table_group(&acl_grp_id1, 2, acl_grp_attr);
if (saistatus != SAI_STATUS_SUCCESS) {
    return saistatus;
}

// Create an ACL table *acl_table_id3* , to be part of this group *acl_grp_id1*
sai_object_id_t acl_table_id3 = 0ULL;
acl_attr_list[0].id = SAI_ACL_TABLE_ATTR_ACL_STAGE;
acl_attr_list[0].value.s32 = SAI_ACL_STAGE_INGRESS;

acl_attr_list[1].id = SAI_ACL_TABLE_GROUP_ATTR_ACL_BIND_POINT_TYPE_LIST;
acl_attr_list[1].value.objlist.count = 1;
acl_attr_list[1].value.objlist.list[0] = SAI_ACL_BIND_POINT_TYPE_PORT;

acl_attr_list[2].id = SAI_ACL_TABLE_ATTR_FIELD_SRC_MAC;
acl_attr_list[2].value.booldata = True;

saistatus = sai_acl_api->create_acl_table(&acl_table_id3, 4, acl_attr_list);
if (saistatus != SAI_STATUS_SUCCESS) {
    return saistatus;
}
--------------------------------------------

Is one of these bind point type assignments redundant OR a requirement:

acl_grp_attr[1].value.objlist.list[0] = SAI_ACL_BIND_POINT_TYPE_PORT;
and
acl_attr_list[1].value.objlist.list[0] = SAI_ACL_BIND_POINT_TYPE_PORT;

Pls clarify or update in the doc.

**Comment by tushar-ty** [comment]
Any inputs on this ?

**Comment by zubinshah** [comment]
Hi @tushar-ty : both acl-group and acl-table accepts an attribute-list "Bind_Point". If you notice int the saiacl.h both these attributes are NOT MANDATORY. 

However, the flow / sequence of operations is important, since an ACL table created can be bound to a bind -point directly, or via an ACL Group (which is created as a separate event). 

I believe in the community we wanted to keep this behavior Implementation dependent, because not all ASIC architectures will need bind point to be known at the time of ACL table creation . However at the time of associating an ACL_TABLE to ACL_GROUP: these bind points are supposed to be a run-time check . For eg. creating an ACL_TABLE with RIF_BIND_POINT , cannot be added to an ACL_GROUP which has a PORT_BIND_POINT. This behavior is still silicon/implementation dependent. 

But both these attributes are not-mandatory.

**Comment by tushar-ty** [comment]
Thanks for the info.
