### ISSUE TITLE
Port Creation behavior from 0.9.4 -> 1.0

### ISSUE THREAD

**Issue by shihjeff** [opencomputeproject/SAI#500]
Hi All,

We have encountered different expectations in the port creation logic post-0.9.4 and wanted to get this clarified so we all users of SAI has the same expectations since doxygen comments are vague on this.  In 0.9.4, sai_create_port_fn didn't exist, so folks expected all ports to be created.  0.9.6 and onward, the API exists and views on initial behavior start to differ.  

Here are the two different views:
1) Since we have sai_create_port_fn in 0.9.6 onward, we should follow the CRUD methodology.  So sai_initialize_switch_fn will NOT create the ports.  Need to call sai_create_port_fn to create the ports after init.
2) Follow 0.9.4 convention, sai_initialize_switch_fn will create all the ports in default mode (like 128x10G or 32x100G).  Only use sai_create/remove_port_fn to change to breakout mode or change port speeds

If we can agree on the proper way moving forward, we can avoid trying to support multiple customer specific expectations.

CC @lguohan / @zubinshah / @atitjain

**Comment by AshokDaparthi** [comment]
Dell - Internal Use - Confidential

Hi,

If i remember correctly based in previous discussions,  suggested to create ports as part of sai_initialize_switch.
It can be default mode ports or exactly based on platform requirements. Since many vendors has config files to init NPU.
This can be passed by profile id/key value pairs concept or provide by the SAI implementation required configuration file format.
If default ports are not matching then adaptor host can create/remove ports.

Along with each port create/remove, SAI should create supported queues/Priroity group on that port.

Regards
Ashok D

**Comment by lguohan** [comment]
agree with ashok. I think it is still following the 0.9.4 convention, now in 1.0, the create_switch will create default ports based on the profile, if there no profile, then it will create default mode. The create/remove port is used for break out mode.

**Comment by shihjeff** [comment]
As per consensus in meeting, we will follow 0.9.4 convention and create the ports in the given profile.
